#ifndef HAZARD_PATCHES_HPP
#define HAZARD_PATCHES_HPP

#define PATCH_SKIP_CD_CHECK 1
#define PATCH_MAKE_ALL_INTROS_SKIPPABLE 0
#define PATCH_SKIP_ALL_INTROS 0
#define PATCH_FILL_EMPTY_MOVIE_LINES 0

#define PATCH_USE_KOREAN_FONT 0

#define PATCH_FIX_UNEQUIP_BUG 0
#define PATCH_FIX_RESISTANCES 0
#define PATCH_FIX_MONSTER_TOHIT_SPEED 0

#endif
