#ifndef HAZARD_USERFLAGENUM_HPP
#define HAZARD_USERFLAGENUM_HPP

#include "HazardTypedef.hpp"

typedef int32_t UserFlagEnum;

struct UserFlag {
  enum Value {
    USERFLAG_IS_ENEMY = 0x1,
    USERFLAG_IS_PLAYER = 0x2,
    USERFLAG_IS_ENEMY_OR_PLAYER = USERFLAG_IS_ENEMY | USERFLAG_IS_PLAYER,
    USERFLAG_IS_TARGETABLE = 0x4,
    USERFLAG_IS_DETECTED = 0x8,

    /* userFlag & (0x10 + 0x20 + 0x40) */
    USERFLAG_SelectableObject = 0x10,
    USERFLAG_TalkableObject = 0x20,
    USERFLAG_OpenObject = 0x30,
    USERFLAG_UnconfirmedObject = 0x40,
    USERFLAG_WarpGate = 0x50,

    USERFLAG_IS_ALIVE = 0x80,

    USERFLAG_IS_UNKNOWN1 = 0x100,
    USERFLAG_IS_UNKNOWN2 = 0x200,
    USERFLAG_IS_UNKNOWN3 = 0x400,
    USERFLAG_IS_UNKNOWN4 = 0x800,

    USERFLAG_CHARACTER_ID1 = 0x1000,
    USERFLAG_CHARACTER_ID2 = 0x2000,
    USERFLAG_CHARACTER_ID3 = 0x4000,

    USERFLAG_SPELLCASTER_MONSTER_RELATED = 0x40000,
    USERFLAG_NORMAL_ENEMY_RELATED_2 = 0x80000,
    USERFLAG_MORE_MONSTER_RELATED = USERFLAG_SPELLCASTER_MONSTER_RELATED | USERFLAG_NORMAL_ENEMY_RELATED_2,
    USERFLAG_MORE_MONSTER_RELATED_EXTRA_FLAG = USERFLAG_SPELLCASTER_MONSTER_RELATED | USERFLAG_NORMAL_ENEMY_RELATED_2 | USERFLAG_IS_ENEMY,
    USERFLAG_ENDBOSSES_RELATED = 0x100000,
    USERFLAG_SPELLCASTER_ENDBOSSES_RELATED = USERFLAG_SPELLCASTER_MONSTER_RELATED | USERFLAG_ENDBOSSES_RELATED,

    USERFLAG_CHARACTER_UNKNOWN = 0x10000,
    USERFLAG_CHARACTER_UNKNOWN_ENEMY_SPELLCASTER = 0x20000,

    USERFLAG_MULTILEVELPROBABILITY = 0x1c0000,

    USERFLAG_WORLDMAP_CHARACTER = 0x200000,

    WANDER_GLOOMY_RELATED = 0x400000,
    RELATES_TO_PUSHED = 0x1000000,

  };
};

#endif
